name: CI

# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        working-directory: ./users_django
        run: python manage.py test
        
      - name: Run coverage
        working-directory: ./users_django
        run: |
          coverage run --source=users manage.py test users
          coverage report
          
      - name: Run linter
        working-directory: ./users_django
        run: DJANGO_SETTINGS_MODULE=users.settings pylint users -d C0114
